<?php
/**
 * AGROVISE - Static export of the public site for GitHub Pages
 *
 * Renders index.php and the five category pages with the current database
 * contents, rewrites .php links to .html, strips the admin links and the
 * product-view tracking beacon (neither can work on a static host), and
 * writes the result plus assets/ and the referenced product images to docs/.
 *
 * Usage (MySQL must be running):
 *   f:/wamp64/bin/php/php8.3.28/php.exe tools/build-pages.php
 *
 * docs/ is generated output: it is wiped and rebuilt on every run.
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$root = dirname(__DIR__);

// Child mode: render one page to stdout (own process, so each page gets a
// clean global scope and the working directory its relative paths expect).
if (($argv[1] ?? '') === '--render') {
    ini_set('display_errors', 'stderr');
    $_SERVER['REQUEST_METHOD'] = 'GET';
    if (isset($argv[3])) {
        $_GET['page'] = $argv[3];
    }
    chdir(dirname($argv[2]));
    require $argv[2];
    exit;
}

$out = $root . '/docs';
$categories = ['insecticides', 'weedicides', 'fungicides', 'granulars', 'micronutrients'];

function renderPage($script, $page = null) {
    $cmd = [PHP_BINARY, __FILE__, '--render', $script];
    if ($page !== null) {
        $cmd[] = (string) $page;
    }
    $proc = proc_open($cmd, [1 => ['pipe', 'w'], 2 => STDERR], $pipes);
    $html = stream_get_contents($pipes[1]);
    fclose($pipes[1]);
    $code = proc_close($proc);
    if ($code !== 0) {
        fwrite(STDERR, "Rendering $script failed (exit $code).\n");
        exit(1);
    }
    return $html;
}

function staticize($html, $slug = null) {
    global $categories;
    $cats = implode('|', $categories);

    $html = preg_replace('#((?:\.\./)?)index\.php#', '$1index.html', $html);
    $html = preg_replace('#href="([^"]*?)(' . $cats . ')\.php#', 'href="$1$2.html', $html);

    // Admin area is PHP-only; drop its menu entries rather than ship dead links
    $html = preg_replace('#\s*<li>\s*<a href="(?:\.\./)?admin/login\.php".*?</a>\s*</li>#s', '', $html);

    // Product-view tracking posts to track.php, which does not exist here
    $html = preg_replace("#\\s*const AV_CSRF = '[^']*';#", '', $html);
    $html = preg_replace("#\\s*const AV_SOURCE = '[^']*';#", '', $html);
    $html = preg_replace('#\s*// Log the product view.*?\.catch\(\(\) => \{\}\);#s', '', $html);

    if ($slug !== null) {
        $html = preg_replace_callback('#href="\?page=(\d+)"#', function ($m) use ($slug) {
            return 'href="' . pageFile($slug, (int) $m[1]) . '"';
        }, $html);
    }
    return $html;
}

function pageFile($slug, $page) {
    return $page <= 1 ? "$slug.html" : "$slug-page-$page.html";
}

function copyTree($src, $dst) {
    if (!is_dir($dst)) {
        mkdir($dst, 0777, true);
    }
    foreach (scandir($src) as $item) {
        if ($item === '.' || $item === '..') continue;
        is_dir("$src/$item") ? copyTree("$src/$item", "$dst/$item") : copy("$src/$item", "$dst/$item");
    }
}

function removeTree($dir) {
    foreach (scandir($dir) as $item) {
        if ($item === '.' || $item === '..') continue;
        is_dir("$dir/$item") ? removeTree("$dir/$item") : unlink("$dir/$item");
    }
    rmdir($dir);
}

// Refuse to wipe a docs/ folder this script did not create
if (is_dir($out)) {
    if (!file_exists("$out/.nojekyll")) {
        fwrite(STDERR, "docs/ exists but was not generated by this script (no .nojekyll marker); not deleting it.\n");
        exit(1);
    }
    removeTree($out);
}
mkdir("$out/categories", 0777, true);

$pages = ['index.html' => staticize(renderPage("$root/index.php"))];

foreach ($categories as $slug) {
    $script = "$root/categories/$slug.php";
    $first = renderPage($script);
    preg_match_all('#href="\?page=(\d+)"#', $first, $m);
    $lastPage = $m[1] ? max(array_map('intval', $m[1])) : 1;

    $pages["categories/" . pageFile($slug, 1)] = staticize($first, $slug);
    for ($p = 2; $p <= $lastPage; $p++) {
        $pages["categories/" . pageFile($slug, $p)] = staticize(renderPage($script, $p), $slug);
    }
}

// Only product images the pages actually show — never the rest of uploads/
// (it also holds private expense-claim bills)
$uploads = [];
foreach ($pages as $file => $html) {
    file_put_contents("$out/$file", $html);
    preg_match_all('#uploads/([A-Za-z0-9._/-]+\.(?:jpe?g|png|gif|webp))#i', $html, $m);
    $uploads = array_merge($uploads, $m[1]);
}
$uploads = array_filter(array_unique($uploads), function ($img) {
    return !str_starts_with($img, 'expenses/') && !str_contains($img, '..');
});
foreach ($uploads as $img) {
    if (!is_dir(dirname("$out/uploads/$img"))) {
        mkdir(dirname("$out/uploads/$img"), 0777, true);
    }
    copy("$root/uploads/$img", "$out/uploads/$img");
}

copyTree("$root/assets", "$out/assets");
file_put_contents("$out/.nojekyll", '');

foreach ($pages as $file => $html) {
    if (preg_match_all('#[\w./-]+\.php\b#', $html, $m)) {
        echo "Warning: $file still references " . implode(', ', array_unique($m[0])) . "\n";
    }
}
echo 'Built ' . count($pages) . ' pages and ' . count($uploads) . " product images into docs/\n";
